### PR TITLE
Skip entities not in the dataset

### PR DESCRIPTION
**Pull request by atehe**
Fixes [ Ukraine NAZK crawler](https://github.com/opensanctions/crawler-planning/issues/71)

@pudo  please take a look when available

### CODE REVIEW

**Comment by pudo** [comment]
This looks good as a fix. Did you check that the missing entities are different than the ones in #72? (see my last comment)

**Comment by atehe** [comment]
you mean the extra dataset in [this issue](https://github.com/opensanctions/crawler-planning/issues/72) right?

I  checked some of them manually, but didnt get any match.
I'm writing a script to go through them now and will let you know how it goes

**Comment by pudo** [comment]
Brilliant! Don't throw that script away, it's going to basically implement #72 :-D

**Comment by atehe** [comment]
Just ran the script and we gett only two matches of missing persons entity in the `/api/v6/shame/ ` endpoint.

**Comment by atehe** [comment]
Awesome! you're right @jbothma. 
We get all except one company id found in the `/api/v6/company-warning/`.
I checked the same for person ids and found 2806/2854 of the missing person ids.

**Comment by jbothma** [comment]
Awesome - thanks. I think let's use that to get related entities then, and info-level log the ones we can't get that way

**Comment by atehe** [comment]
Alright...
Do i also add the companies and people in the other endpoints as  sanctioned entities as well?

**Comment by pudo** [comment]
If they're one graph I would add them all to the dataset but not mark them with topic sanction

**Comment by atehe** [comment]
Ok got it...
thank you

**Comment by atehe** [comment]
@pudo I've added the other endpoints for persons and companies.
The crawler first checks them all to get a list of existing companies and  flags any one that is not in the list while scraping. 
The endpoints are cralwled similarly and the sanction role is added only to entities gotten from the main company and person endpoints

**Comment by jbothma** [comment]
@atehe Did you check, do the company IDs on the different compoany endpoints intersect? And if so, do you get the same company back from the different endpoints? Or is it possible that you'd get two companies' details added to the dataset on the same ID, coming from different datasets?

**Comment by atehe** [comment]
I just checked @jbothma and there is no intersections of the ids in the different endpoints.
I could add a tracker that checks if a company/person has been crawled to the crawler though or what do you think?

**Comment by jbothma** [comment]
Yeah i think it's a good idea to warn and skip if they intersect. Thanks!

**Comment by atehe** [comment]
@jbothma I've added a check to warn and skip persons/companies that have already been crawled

**Comment by jbothma** [comment]
Thanks @atehe - After a night's rest I realised that check should raise instead of warn, otherwise we might still be emitting relationships to the wrong entity - something like this? https://github.com/opensanctions/opensanctions/commit/c16fc223877b385f316d154948b924ec0c525c5a#diff-172ca37747291b1feac175161689237ecc0af41cb77c5bdcd2349deeda02aa94R211

Also I see logs like 
```
[warning  ] Unexpected data found          [ua_nabc_sanctions] data={'reasoning_en': '"The company supplies metal-cutting machines, components and...
```

which is `context.audit` doing its job nicely. Could you add the reasons to the entity as notes?

@pudo should we still emit sanctions for the related non-sanctioned entities or skip that as well? Should they get the `sanction.linked topic`?

**Comment by pudo** [comment]
Hm, `sanction.linked` will be assigned automatically - we don't need to do that in this dataset. I would definitely not emit a `Sanction` object, but perhaps we can find some other topic that captures the intent of these subcollections?

**Comment by atehe** [comment]
Alright noted.

**Pull request merged**
