### PR TITLE
Feature added gb nca most wanted

### PR DESCRIPTION
**Pull request by uberfresh**

### CODE REVIEW

**Comment by uberfresh** [comment]
@pudo Hey can you review it ? :smiley: 
Issue: https://github.com/opensanctions/opensanctions/issues/248

**Comment by pudo** [comment]
Looks really good, I'd be happy to merge. the most brittle thing is probably the `fix_label` function - is there maybe a more lightweight solution by selecting a more specific child element, or running it through a standardized func like `from normality import slugify`?

**Comment by uberfresh** [comment]
> from normality import slugify

Hi @pudo 

These are the most specific child elements that change on every criminal page. So I can't select more specific but I have added 
`from normality import slugify` depending on your suggestion.

**Comment by pudo** [comment]
Great! Let's do it :)

**Pull request merged**
