### PR TITLE
adding Malaysia financial consumer alert list

### PR DESCRIPTION
**Pull request by bgmello**
Fixes opensanctions/crawler-planning#96

### CODE REVIEW

**Comment by jbothma** [comment]
Could you save the html file in the data dir and then load and parse the file from there? a la https://github.com/opensanctions/opensanctions/blob/main/datasets/lt/fiu_freezes/crawler.py#L13

and one of these to remind us in 3 months to update

```python
def crawl(context):
    if datetime.datetime.now() > datetime.datetime(2024, 9, 15):
        context.log.warn("Check if there's an update of the data behind the bot check.")
```

Remember for these we set coverage.frequency: never, coverage.end to the date you save the data, and add a note in the description that the data is only updated occasionally

**Comment by bgmello** [comment]
Done

**Comment by jbothma** [comment]
I'm just confirming the most appropriate topic for this

**Comment by pudo** [comment]
If we can't quite agree to the topic, let's default to `poi` as you suggested @jbothma  :)

**Pull request merged**
