### PR TITLE
creating lookups

### PR DESCRIPTION
**Pull request by bgmello**

### CODE REVIEW

**Comment by pudo** [comment]
Aaah damn - we got our wires crossed here. We were just missing these here: 

https://github.com/opensanctions/opensanctions/blob/main/datasets/ph/sec_advisories/ph_sec_advisories.yaml#L330-L403

**Comment by bgmello** [comment]
No worries, I'll fix to use your code

**Comment by pudo** [comment]
Very much appreciated!!

**Comment by bgmello** [comment]
Done on #1010

**Pull request closed without merging**
