### PR TITLE
use zf context manager instead of tmpfile

### PR DESCRIPTION
**Pull request by SimonThordal**
Probably not what causes the OOM, but I cannot replicate locally, so working a bit in the dark.

### CODE REVIEW

**Comment by pudo** [comment]
Ha, I made the opposite change in order to get rid of the memory leak - so it's definitely not the zip handling, I guess. Really curious what the issue might be :/

**Comment by pudo** [comment]
I've done a bit of a log read and am pretty convinced that it's not actually the crawler but the exporter that fails. This likely points to some anomaly with the data, but I'm going to first just up the memory to see how high the spike goes if left to itself.

**Comment by SimonThordal** [comment]
> I've done a bit of a log read and am pretty convinced that it's not actually the crawler but the exporter that fails. This likely points to some anomaly with the data, but I'm going to first just up the memory to see how high the spike goes if left to itself.

That makes sense considering the crawl itself did not spike locally.

**Comment by pudo** [comment]
Ok so the data is in fact in some ways buggy, and OO is also considering dropping it. Let's not waste more time here.

**Pull request closed without merging**
