### PR TITLE
adding New Hampshire Medicare Exclusions Crawler

### PR DESCRIPTION
**Pull request by bgmello**

### CODE REVIEW

**Comment by bgmello** [comment]
Same as PR #1204, I wasn't able to use the `context` methods

**Review by jbothma — COMMENTED** [review]
I'm missing Jennifer Lynn from the resulting data. Maybe I'm being silly but could you check if there's a bug?

**Comment by bgmello** [comment]
I can see Jennifer Lynn in the `entities.ftm.json`:

Screenshot 2024-09-04 at 10 55 01

The id is `us-mednh-bb589665b25a0bacf2bb74e48cb4f137a6e1fb39`

**Comment by jbothma** [comment]
Weird - after deleting the data file and letting it re-fetch, I find them.

Thanks for the fixes. Looks like some imports are snagging. Once it's green I can merge.

**Pull request merged**
